# This is a config file specifically for Gruntwork sandbox accounts to only clean up S3 buckets that we know for sure
# are used for testing.
s3:
  include:
    names_regex:
      - "^cloudfront-example-[a-zA-Z0-9]{6}\\.gruntwork\\.in.*"
      - "^gruntwork-terratest-[a-zA-Z0-9]{6}$"
      - "^gw-cis-aws-config-all-regions-[a-zA-Z0-9]{6}-.*"
      - "^gruntwork-test-[a-zA-Z0-9]{6}-config-test$"
      - "^houston-static-[a-zA-Z0-9]{12}.*"
      - "^cloud-nuke-test-[a-zA-Z0-9]{12}.*"
      - "^cloud-nuke-test-[a-zA-Z0-9]{6}-bucket$"
      - "^alb-alb-[a-zA-Z0-9]{6}-access-logs$"
      - "^kafka-zk-standalone-[a-zA-Z0-9]{6}$"
      - "^zookeeper-cluster-test-[a-zA-Z0-9]{6}$"
      - "^terragrunt-test-bucket-[a-zA-Z0-9]{6}.*"

SecretsManager:
  include:
    names_regex:
      - "^test-name-[a-zA-Z0-9]{6}$"
      - "^GruntworkSampleAppFrontendCA[a-zA-Z0-9]{6}$"
      - "^GruntworkSampleAppBackendCA[a-zA-Z0-9]{6}$"
      - "^RDSDBConfig[a-zA-Z0-9]{6}$"
      - "ECRDeployRunnerTestSSHKey-[a-zA-Z0-9]{6}$"
      - "ECRDeployRunnerTestGitPAT-[a-zA-Z0-9]{6}$"

NatGateway:
  # There is a bug in the cloud-nuke config where exclude does not work by itself, so we add a null include rule that
  # includes everything.
  # See https://github.com/gruntwork-io/cloud-nuke/issues/198 for more info.
  include:
    names_regex:
      - ".*"
  exclude:
    names_regex:
      # We have an active ECS Deploy Runner running in the sandbox environment for sales demos, and this NAT gateway is
      # critical for that.
      - "^ecs-deploy-runner-v2-nat-gateway-0$"
